typography_spectrum: 1
color:
  brandColors:
    - '#151517'
    - '#f6f2e9'
    - '#91ddd1'
    - '#796f65'
    - '#62aba2'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89003
analytics:
  google: null
  facebook: null
  twitter: null
name: February
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: BE LIKE NO OTHER
purpose: []
