name: February
favicon: null
layout_spectrum: 0.4780439715832472
typography_spectrum: 0.37306672031991184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09766081720590591
  lightness: 0.5766845364123583
  saturation: 0.6170873346272856
  rhythmicContrast: 0.07621206250041723
purpose: []
